version: '3.8'
services:
  app-backend:
    # This tells Docker to go find the image on Docker Hub
    image: maulik747/water-backend:latest 
    ports:
      - "8080:8080"
    restart: always

  app-frontend:
    image: maulik747/water-frontend:latest
    ports:
      - "80:80"
    restart: always